name: first
on:
  push

jobs:
  runcommands:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run single cmd
        run: echo "hello"
      - name: Run multiple cmd
        run: | 
          echo "THis is"
          echo "multiple"
